---
- name: Update and upgrade the package list
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install basic packages
  ansible.builtin.apt:
    name:
      - vim
      - sudo
      - ufw
      - openssh-server
      - ca-certificates
      - curl
      - wget
      - rsync
      - net-tools
      - tcpdump
      - procps
    state: present

- name: System limits and sysctl tuning
  ansible.builtin.import_tasks: tuning.yml
  when: base_host_sys_tuning_enable | bool

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ ansible_facts['hostname'] }}"

- name: Enable and start the ssh service on specified port
  ansible.builtin.systemd:
    name: ssh
    enabled: true
    state: started

- name: Configure swapfile
  become: true
  block:
    - name: Create swapfile
      ansible.builtin.command: "dd if=/dev/zero of={{ base_host_swapfile_path }} bs=1M count={{ base_host_swapfile_size_mb }}"
      args:
        creates: "{{ base_host_swapfile_path }}"
      register: base_host_swapfile_create

    - name: Set permissions for swapfile
      ansible.builtin.file:
        path: "{{ base_host_swapfile_path }}"
        owner: root
        group: root
        mode: "0600"

    - name: Format swapfile
      ansible.builtin.command: "mkswap {{ base_host_swapfile_path }}"
      when: base_host_swapfile_create.changed
      changed_when: true

    - name: Enable swapfile
      ansible.builtin.command: "swapon {{ base_host_swapfile_path }}"
      when: base_host_swapfile_create.changed
      changed_when: true

    - name: Ensure swapfile is enabled at boot
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "{{ base_host_swapfile_path }} none swap sw 0 0"
        regexp: "^{{ base_host_swapfile_path | regex_escape }}\\s+none\\s+swap\\s"
