base_host_swapfile_size_mb: "{{ ansible_memtotal_mb }}"
base_host_swapfile_path: "/swapfile"

base_host_ssh_port: 2222

# Firewall role
firewall_enable: true
firewall_allow_tcp: []
firewall_allow_udp: []

# Docker role
docker_install: true
docker_enable_service: true
docker_install_compose: true
docker_users:
  - "{{ ansible_user_id }}"
  
