---
- name: Ensure UFW is installed (Debian/Ubuntu)
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: ansible_facts.os_family == 'Debian'

- name: Set default incoming policy
  community.general.ufw:
    direction: incoming
    policy: "{{ firewall_default_incoming_policy }}"
  when: firewall_enable | bool

- name: Set default outgoing policy
  community.general.ufw:
    direction: outgoing
    policy: "{{ firewall_default_outgoing_policy }}"
  when: firewall_enable | bool

- name: Allow SSH (configured port)
  community.general.ufw:
    rule: allow
    port: "{{ ansible_port | default(base_host_ssh_port | default(22)) }}"
    proto: tcp
  when: firewall_enable | bool

- name: Allow TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ (item.port if (item is mapping) else item) }}"
    proto: tcp
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ firewall_allow_tcp | default([]) }}"
  when:
    - firewall_enable | bool
    - firewall_allow_tcp is defined

- name: Allow UDP ports
  community.general.ufw:
    rule: allow
    port: "{{ (item.port if (item is mapping) else item) }}"
    proto: udp
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ firewall_allow_udp | default([]) }}"
  when:
    - firewall_enable | bool
    - firewall_allow_udp is defined

- name: Enable UFW
  community.general.ufw:
    state: enabled
  when: firewall_enable | bool
