---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker.io
      - "{{ 'docker-compose' if (docker_install_compose | bool) else omit }}"
    state: present
